#!/usr/bin/env bash

# run with sudo

INSTDIR=/usr/share/battalert

# install application
rsync --recursive --exclude=.git --exclude=*.log . $INSTDIR
if test -f "/usr/bin/battalert"; then
  rm -f /usr/bin/battalert
fi

# create symlink for executable
ln -s $INSTDIR/battalert.py /usr/bin/battalert

# create symlink for cronjob
ln -s $INSTDIR/battalert.cron /etc/cron.d/battalert
