#!/usr/bin/env bash

# run with sudo

INSTDIR=/usr/share/battalert

# remove installation dir
rm -rf $INSTDIR

# remove bin symlink
rm -f /usr/bin/battalert

# remove config symlink
rm -f /etc/battalert

# remove cron job
rm -f /etc/cron.d/battalert
